//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.Components.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.etransparencia.com.br/mg.varginha/webservice/aws_nfe.aspx")]
        public string NFe_Components_br_com_etransparencia_nfe_varginha_p_ws_nfe {
            get {
                return ((string)(this["NFe_Components_br_com_etransparencia_nfe_varginha_p_ws_nfe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomologacao.etransparencia.com.br/mg.varginha/webservice/aws_nfe.aspx")]
        public string NFe_Components_br_com_etransparencia_nfehomologacao_varginha_h_ws_nfe {
            get {
                return ((string)(this["NFe_Components_br_com_etransparencia_nfehomologacao_varginha_h_ws_nfe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.etransparencia.com.br/mg.varginha/webservice/aws_nfe.aspx")]
        public string NFe_Components_br_com_etransparencia_nfe_p_ws_nfe {
            get {
                return ((string)(this["NFe_Components_br_com_etransparencia_nfe_p_ws_nfe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://189.56.68.34:8080/ws_araras/nfseservice.svc")]
        public string NFe_Components_PArarasSP_NfseService {
            get {
                return ((string)(this["NFe_Components_PArarasSP_NfseService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tangaradaserra.prefeitura.rlz.com.br:8070/webservice/nfse")]
        public string NFe_Components_HTangaraDaSerraMT_NfseWSService {
            get {
                return ((string)(this["NFe_Components_HTangaraDaSerraMT_NfseWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cidadaoonline.tangaradaserra.mt.gov.br/webservice/nfse")]
        public string NFe_Components_PTangaraDaSerraMT_NfseWSService {
            get {
                return ((string)(this["NFe_Components_PTangaraDaSerraMT_NfseWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://transparencia.castanhal.pa.gov.br:8086/NFSe.Portal.Integracao/Services.svc" +
            "")]
        public string NFe_Components_Castanhal_NFSeIntegracao {
            get {
                return ((string)(this["NFe_Components_Castanhal_NFSeIntegracao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://notafiscal.linhares.es.gov.br:80/el-nfse/RpsService")]
        public string NFe_Components_PLinharesES_RpsServiceService {
            get {
                return ((string)(this["NFe_Components_PLinharesES_RpsServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://testeiss.londrina.pr.gov.br/ws/v1_03/sigiss_ws.php")]
        public string NFe_Components_br_gov_pr_londrina_testeiss_h_ModuloEmissorNFSe {
            get {
                return ((string)(this["NFe_Components_br_gov_pr_londrina_testeiss_h_ModuloEmissorNFSe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://iss.londrina.pr.gov.br:443/ws/v1_03/sigiss_ws.php")]
        public string NFe_Components_br_gov_pr_londrina_iss_ModuloEmissorNFSe {
            get {
                return ((string)(this["NFe_Components_br_gov_pr_londrina_iss_ModuloEmissorNFSe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://testepetropolis.sigiss.com.br:443/testepetropolis/ws/sigiss_ws.php")]
        public string NFe_Components_HPetropolisRJ_WebService_SigISS {
            get {
                return ((string)(this["NFe_Components_HPetropolisRJ_WebService_SigISS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://petropolis.sigiss.com.br:443/petropolis/ws/sigiss_ws.php")]
        public string NFe_Components_PPetropolisRJ_WebService_SigISS {
            get {
                return ((string)(this["NFe_Components_PPetropolisRJ_WebService_SigISS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/IssWeb-ejb/IssWebWS/IssWebWS")]
        public string NFe_Components_br_net_cosmorama_fiorilli_p_IssWebWS {
            get {
                return ((string)(this["NFe_Components_br_net_cosmorama_fiorilli_p_IssWebWS"]));
            }
        }
    }
}
